/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/certificates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_admin_certificates_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/certificates/{certificate_id}/revoke/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_admin_certificates_revoke_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/teams/import/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_admin_teams_import_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/demo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_demo_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/certificates/{token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_certificates_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_challenges_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{challenge_id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["v1_challenges_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{no}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_challenges_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_event_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_leaderboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountOutput: {
            /** Format: uuid */
            id: string;
            username: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["RoleEnum"];
        };
        AssetOutput: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["TypeEnum"];
            /** Format: uri */
            url: string;
            downloadable: boolean;
            /** Format: uri */
            transcript_url: string | null;
        };
        CertificateOutput: {
            /** Format: uuid */
            id: string;
            team_name: string;
            event_name: string;
            rank: number;
            /** Format: double */
            score: number;
            /** Format: date-time */
            issued_at: string;
        };
        ChallengeOutput: {
            /** Format: uuid */
            id: string;
            no: number;
            title: string;
            question: string;
            score: number;
            solved: boolean;
            unlocked: boolean;
            assets: components["schemas"]["AssetOutput"][];
        };
        CsrfOutput: {
            csrfToken: string;
        };
        DetailOutput: {
            detail: string;
        };
        EventOutput: {
            demo_mode: boolean;
            name: string;
            /** Format: date-time */
            starts_at: string | null;
            /** Format: date-time */
            ends_at: string | null;
            status: components["schemas"]["StatusEnum"];
            /** Format: date-time */
            server_time: string;
        };
        ImportInputRequest: {
            rows: components["schemas"]["ImportRowRequest"][];
            /** @default true */
            dry_run: boolean;
            /** @default false */
            reset_existing: boolean;
        };
        ImportOutput: {
            dry_run: boolean;
            rows: components["schemas"]["ImportResultRow"][];
        };
        ImportResultRow: {
            /** Format: email */
            email: string;
            username: string;
            action: string;
            password?: string;
        };
        ImportRowRequest: {
            username: string;
            /** Format: email */
            email: string;
        };
        IssueInputRequest: {
            /** Format: uuid */
            team_id: string;
        };
        IssueOutput: {
            /** Format: uri */
            url: string;
            certificate: components["schemas"]["CertificateOutput"];
        };
        LeaderboardOutput: {
            teams: components["schemas"]["StandingOutput"][];
            series: components["schemas"]["SeriesOutput"][];
            /** Format: date-time */
            generated_at: string;
        };
        LoginInputRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        PointOutput: {
            /** Format: date-time */
            time: string;
            /** Format: double */
            score: number;
        };
        /**
         * @description * `participant` - participant
         *     * `admin` - admin
         * @enum {string}
         */
        RoleEnum: "participant" | "admin";
        SeriesOutput: {
            /** Format: uuid */
            id: string;
            name: string;
            points: components["schemas"]["PointOutput"][];
        };
        StandingOutput: {
            /** Format: uuid */
            id: string;
            username: string;
            rank: number;
            /** Format: double */
            score: number;
            solved: number;
        };
        /**
         * @description * `unconfigured` - unconfigured
         *     * `upcoming` - upcoming
         *     * `live` - live
         *     * `ended` - ended
         * @enum {string}
         */
        StatusEnum: "unconfigured" | "upcoming" | "live" | "ended";
        SubmitInputRequest: {
            flag: string;
        };
        SubmitOutput: {
            detail: string;
            already_solved: boolean;
        };
        /**
         * @description * `audio` - audio
         *     * `video` - video
         *     * `image` - image
         *     * `zip` - zip
         *     * `pdf` - pdf
         *     * `srt` - srt
         *     * `url` - url
         * @enum {string}
         */
        TypeEnum: "audio" | "video" | "image" | "zip" | "pdf" | "srt" | "url";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v1_admin_certificates_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["IssueInputRequest"];
                "multipart/form-data": components["schemas"]["IssueInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueOutput"];
                };
            };
        };
    };
    v1_admin_certificates_revoke_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailOutput"];
                };
            };
        };
    };
    v1_admin_teams_import_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ImportInputRequest"];
                "multipart/form-data": components["schemas"]["ImportInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportOutput"];
                };
            };
        };
    };
    v1_auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfOutput"];
                };
            };
        };
    };
    v1_auth_demo_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOutput"];
                };
            };
        };
    };
    v1_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginInputRequest"];
                "multipart/form-data": components["schemas"]["LoginInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOutput"];
                };
            };
        };
    };
    v1_auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailOutput"];
                };
            };
        };
    };
    v1_auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOutput"];
                };
            };
        };
    };
    v1_certificates_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOutput"];
                };
            };
        };
    };
    v1_challenges_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOutput"][];
                };
            };
        };
    };
    v1_challenges_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                challenge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitInputRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SubmitInputRequest"];
                "multipart/form-data": components["schemas"]["SubmitInputRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitOutput"];
                };
            };
        };
    };
    v1_challenges_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOutput"];
                };
            };
        };
    };
    v1_event_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventOutput"];
                };
            };
        };
    };
    v1_leaderboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardOutput"];
                };
            };
        };
    };
}
