# Generated by Django 5.2.17 on 2026-09-17 16:57

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("no", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("question", models.TextField(blank=True)),
                (
                    "score",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("flag_hash", models.CharField(editable=False, max_length=256)),
            ],
            options={
                "ordering": ["no"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(
                        max_length=2000,
                        validators=[django.core.validators.URLValidator(schemes=["https"])],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("audio", "audio"),
                            ("video", "video"),
                            ("image", "image"),
                            ("zip", "zip"),
                            ("pdf", "pdf"),
                            ("srt", "srt"),
                            ("url", "url"),
                        ],
                        max_length=10,
                    ),
                ),
                ("downloadable", models.BooleanField(default=True)),
                (
                    "transcript",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="competition.asset",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="competition.challenge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="TechHunt · IIIT Vadodara", max_length=150)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="singleton_event")
                ],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="competition.challenge",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["time", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("team", "challenge"), name="unique_team_solve"),
                    models.UniqueConstraint(
                        fields=("challenge", "position"), name="unique_solve_position"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("position__gte", 1)), name="positive_solve_position"
                    ),
                ],
            },
        ),
    ]
